version: "3"

services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      - MIX_ENV=dev
    volumes:
      - ./:/opt/app
    working_dir: /opt/app
    command: ["/bin/sh", "-c", "tail -f /dev/null"]